version: 2.1

aliases:
  - &yarn_cache_key
    v2-{{ checksum "yarn.lock" }}

executors:
  docker-node:
    docker:
      - image: circleci/node:12.8.1-stretch
    working_directory: ~/worship-mate/
    shell: /bin/bash -eux -o pipefail

commands:
  install_yarn_and_deps:
    description: Install yarn dependencies
    steps:
      - restore_cache:
          key: *yarn_cache_key
      - run:
          name: Install external dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: *yarn_cache_key
          paths:
            - node_modules
            - client/node_modules

jobs:
  build:
    executor: docker-node
    steps:
      - checkout
      - install_yarn_and_deps
      - run: yarn workspaces run build

  lint:
    executor: docker-node
    steps:
      - checkout
      - install_yarn_and_deps
      - run: yarn lint
      - run: yarn workspaces run typecheck

  test:
    executor: docker-node
    steps:
      - checkout
      - install_yarn_and_deps
      - run: yarn workspaces run test

workflows:
  version: 2

  build_and_test:
    jobs:
      - build
      - lint
      - test
