version: 2.1

aliases:
  - &yarn_cache_key v2-yarn-{{ checksum "yarn.lock" }}
  - &next_cache_key v1-next-{{ checksum "yarn.lock" }}
  - &ci_executor
    working_directory: ~/worship_mate/
    shell: /bin/bash -eux -o pipefail
  - &docker_node_image circleci/node:12.8.1-stretch

orbs:
  codecov: codecov/codecov@1.0.2

executors:
  docker_node:
    <<: *ci_executor
    docker:
      - image: *docker_node_image

  docker_node_postgres:
    <<: *ci_executor
    docker:
      - image: *docker_node_image
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_DB: worship_mate
    environment:
      PGUSER: postgres
      PGDATABASE: worship_mate

commands:
  install_yarn_and_deps:
    steps:
      - restore_cache:
          key: *yarn_cache_key
      - run:
          name: Install external dependencies
          command: yarn install --immutable
      - save_cache:
          key: *yarn_cache_key
          paths:
            - .yarn/cache/

jobs:
  test_server:
    executor: docker_node_postgres
    steps:
      - checkout
      - install_yarn_and_deps

      - run: yarn server typecheck

      - run: yarn server test --coverage
      - codecov/upload:
          file: server/coverage/lcov.info

      - run: yarn server test:e2e --coverage
      - codecov/upload:
          file: server/coverage/lcov.info

  build_client:
    executor: docker_node_postgres
    steps:
      - checkout
      - install_yarn_and_deps

      # need running server for getStaticProps in NextJS build
      - run: yarn server migrate up
      - run:
          command: yarn server start:prod
          background: true

      # builds client for testing in CI -- production will
      # build its own Next.js app
      - restore_cache:
          key: *next_cache_key
      - run: yarn client build
      - save_cache:
          key: *next_cache_key
          paths:
            - client/.next/cache

      - persist_to_workspace:
          root: .
          paths:
            - client/.next

  test_client:
    executor: docker_node
    steps:
      - checkout
      - install_yarn_and_deps

      - run: yarn client typecheck

      - run: yarn client test --coverage
      - codecov/upload:
          file: client/coverage/lcov.info

  test_cypress:
    executor: docker_node_postgres
    steps:
      - checkout
      - attach_workspace:
          at: .
      - install_yarn_and_deps

      - run:
          name: Run server in background
          command: yarn server start:prod
          background: true
      - run:
          name: Run client in background
          command: yarn client start:prod
          background: true
      - run:
          name: Run database test server in background
          command: yarn server db:start-test-server
          background: true

      - run:
          name: Wait for services
          command: yarn wait-on tcp:4000 tcp:3000 tcp:4040

      - run:
          name: Run Cypress tests
          command: yarn client cypress run
      - store_artifacts:
          path: /client/cypress/videos/
      - store_artifacts:
          path: /client/cypress/screenshots/

  lint_all:
    executor: docker_node
    steps:
      - checkout
      - install_yarn_and_deps

      - run:
          name: Install pre-commit
          command: curl https://pre-commit.com/install-local.py | python -
      - run:
          name: Run pre-commit
          command: pre-commit run --all-files

      - run:
          name: Check that server GraphQL files are up to date
          command: |
            yarn server codegen
            git diff --exit-code server/
      - run:
          name: Check that client GraphQL files are up to date
          command: |
            yarn client codegen
            git diff --exit-code client/

workflows:
  version: 2

  build_and_test:
    jobs:
      - test_server
      - build_client
      - test_client
      - test_cypress:
          requires:
            - build_client
      - lint_all
