version: 2.1

aliases:
  - &yarn_cache_key v1-yarn-{{ checksum "yarn.lock" }}
  - &next_cache_key v1-next-{{ checksum "yarn.lock" }}

orbs:
  codecov: codecov/codecov@1.0.2

executors:
  docker-node:
    docker:
      - image: circleci/node:12.8.1-stretch
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_DB: worship_mate
    working_directory: ~/worship-mate/
    shell: /bin/bash -eux -o pipefail

commands:
  install_yarn_and_deps:
    description: Install yarn dependencies
    steps:
      - restore_cache:
          key: *yarn_cache_key
      - run:
          name: Install external dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: *yarn_cache_key
          paths:
            - node_modules
            - client/node_modules

jobs:
  build:
    executor: docker-node
    steps:
      - checkout
      - install_yarn_and_deps
      - restore_cache:
          key: *next_cache_key
      - run: yarn workspaces run build
      - save_cache:
          key: *next_cache_key
          paths:
            - client/.next/cache

  lint:
    executor: docker-node
    steps:
      - checkout
      - install_yarn_and_deps
      - run: yarn lint .
      - run: yarn workspaces run typecheck

  test:
    executor: docker-node
    steps:
      - checkout
      - install_yarn_and_deps
      - run: yarn workspaces run test --coverage
      - codecov/upload:
          file: client/coverage/lcov.info

workflows:
  version: 2

  build_and_test:
    jobs:
      - build
      - lint
      - test
